[package]
name = "ifsc_rau_cncinterface"
version = "0.0.0"
description = "A Tauri App"
authors = ["lalvesl"]
license = "MIT"
repository = "https://github.com/lalvesl/ifscRauCNCInterface"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ifsc_rau_cnc_interface_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22.0"
qrcode-generator = "4.1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.1", features = [
  "fs-read-file",
  "fs-read-dir",
  "shell-open",
] }
tauri-plugin-shell = "2"
urlencoding = "2.1.3"
