FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install --assume-yes --no-install-recommends \
        gnupg2 \
        ca-certificates \
        build-essential \
        curl \
        wget \
        file \
        libwebkit2gtk-4.0-dev \
        libssl-dev \
        libgtk-3-dev \
        libayatana-appindicator3-dev \
        librsvg2-dev \
        openssl && \
    apt-get autoclean && \
    apt-get autoremove -y

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --target armv7-unknown-linux-gnueabihf

WORKDIR /app

ENV CARGO_TARGET_DIR=/app/target \
    PATH="/root/.cargo/bin:$PATH"

RUN rustup target add wasm32-unknown-unknown && \
    cargo install trunk && \
    cargo install wasm-bindgen-cli && \
    cargo install tauri-cli

CMD ["sh", "-c", "PATH=\"/root/.cargo/bin:$PATH\" && CARGO_TARGET_DIR=\"/app/target/\" && ls -lha && cargo tauri dev"]
